export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_MANY_CLIENTS = 'ADD_MANY_CLIENTS';
export const REMOVE_LAST_CLIENT = 'REMOVE_LAST_CLIENT';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
